permalink: /:title

gems:
  - jekyll-sitemap

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

safe: true
lsi: false
highlighter: true

name: SEN Symposium
title: SEN Symposium

production_url: http://www.sen-symposium.nl

exclude: ["README.md"]

blogname: SEN Symposium Blog 
description: SEN Symposium Blog.
url: http://www.sen-symposium.nl
